apiVersion: v1
kind: Pod
metadata:
 name: webapp-pod
 labels:
    name: kodekloud/simple-webapp-mysql
spec: 
 containers: 
   envFrom:
    - secretRef:
        name: db-secret
   image: kodekloud/webapp-color
   name: webapp-color

