apiVersion: v1
kind: Pod
metadata:
 name: webapp-color
 labels:
    name: webapp-color
spec: 
 containers: 
 - env:
   - name: APP_COLOR
     valueFrom: 
       configMapKeyRef:
        name: webapp-config-map
        key: APP_COLOR
   image: kodekloud/webapp-color
   name: webapp-color

