apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-02-02T20:57:55Z"
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
  resourceVersion: "781"
  uid: adbe28fb-4f9c-4476-825a-b8bebb0ff39b
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: green
    image: kodekloud/webapp-color
    imagePullPolicy: Always
    name: webapp-color
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true