apiVersion: v1
kind: ReplicationController
metadata:
 name: rc-replica
 labels:
  type: front-end
  env: uat
spec:
   template:
    metadata: 
     name: nginx
     labels:
      app: web
      type: uat
    spec:
     containers:
      - name: web-uat
        image: nginx
   replicas: 3