apiVersion: v1
kind: Pod
metadata:
  labels:
    component: static-busybox
    tier: control-plane
  name: static-busybox
  namespace: kube-system
spec:
  containers:
  - command: ["/bin/sh", "-ec", "sleep 1000"]
    image: busybox
    imagePullPolicy: IfNotPresent
